version: '3'
services:
  mysql:
    image: haitbourhim/csa-database:latest
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u user -ppassword" ]
      interval: 10s
      timeout: 5s
      retries: 3

  spring-app:
    image: haitbourhim/csa-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ubo_db?useSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  react-app:
    image: haitbourhim/csa-frontend:latest
    ports:
      - "3000:3000"