name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build React App
        run: |
          npm install
          npm run build

      - name: Set up Docker
        uses: docker/login-action@v1
        with:
          username: "haitbourhim"
          password: "zissizriddikilos"

      - name: Build and push Docker image
        if: success()
        run: |
          docker build -t haitbourhim/csa-frontend:latest .
          docker push haitbourhim/csa-frontend:latest
